# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Superpet < Formula
  desc "Simple command-line snippet and environment manager"
  homepage "https://github.com/ramiawar/superpet"
  version "0.6.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ramiawar/superpet/releases/download/v0.6.2/superpet_0.6.2_darwin_arm64.tar.gz"
      sha256 "2aaecef98995ccfa9daf3e395bbc150d3cef20f378fc49a88d2ca28aef2d975b"

      def install
        bin.install Dir['superpet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ramiawar/superpet/releases/download/v0.6.2/superpet_0.6.2_darwin_amd64.tar.gz"
      sha256 "210a3c7e0014f84f5802ff0282a14ed242b34de70f654325f9fefb8f5b7ffdea"

      def install
        bin.install Dir['superpet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ramiawar/superpet/releases/download/v0.6.2/superpet_0.6.2_linux_arm64.tar.gz"
      sha256 "fbe6b5984966ef66e11b0516174c50389dbbc2f668bec1a0c28705c230fd56b7"

      def install
        bin.install Dir['superpet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ramiawar/superpet/releases/download/v0.6.2/superpet_0.6.2_linux_amd64.tar.gz"
      sha256 "21cbef0b22d32cdf2118a8f85076ac0af3d1542c595df57d28d72df5708b1aff"

      def install
        bin.install Dir['superpet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ramiawar/superpet/releases/download/v0.6.2/superpet_0.6.2_linux_armv6.tar.gz"
      sha256 "e2af163f1400d7f872e1e2634e8b0eecea33654f9a43b09800d86c8d33a66b6e"

      def install
        bin.install Dir['superpet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
  end

  depends_on "fzf"

  test do
    system "#{bin}/pet"
  end
end
